apiVersion: v1
kind: Service
metadata:
  name: kb-automate
  namespace: namespace-workflow-1712296832898
spec:
  type: LoadBalancer
  selector:
    app: kb-automate
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000